// The generator catalog. One entry per kind of document the platform drafts.
//
// Rules for adding an entry:
//   1. `key` is stored in the database as doc_type. Pick it once, never reuse it.
//   2. Widen the doc_type CHECK constraints in a migration in the same change,
//      or every insert for the new kind fails at runtime. The parity test in
//      lib/guardrails/document-generator-parity.test.ts fails the build when
//      the registry and the migrations disagree, so this cannot ship half-done.
//   3. Drafting guidance goes in `guidance`. Never ship a pre-filled field value
//      — see lib/guardrails/generator-asset-prefill.test.ts for what that costs.
//   4. humanReviewRequired is true for anything that authorises work, carries
//      legal weight, disciplines a person, or is signed in the field.

import type { GeneratorSpec } from "./types";

// ---------------------------------------------------------------------------
// Field Safety — used at the work face, often signed on the jobsite
// ---------------------------------------------------------------------------

const fieldSafety: readonly GeneratorSpec[] = [
  {
    key: "jsa",
    label: "Job Safety Analysis (JSA)",
    group: "Field Safety",
    summary: "Breaks a task into steps, with the hazard and the control for each step.",
    documentKind: "Job Safety Analysis (JSA)",
    fieldUse: true,
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Overhead Pipe Rack Demolition — Bay 4",
    sections: [
      "Task & Location",
      "Crew, Competent Person & Training Required",
      "Required PPE",
      "Permits & Pre-Task Requirements",
      "Task Steps, Hazards & Controls",
      "Stop Work Triggers",
      "Emergency Response & Rescue",
      "Crew Acknowledgment",
    ],
    guidance: [
      'Write "Task Steps, Hazards & Controls" as a numbered sequence in the order the work is actually performed. Each item shall read "Step — Hazard — Control", where the control is a specific verifiable action, not a restatement of the hazard.',
      "Order controls by the hierarchy of controls: elimination, substitution, engineering, administrative, then PPE. PPE shall never stand alone as the only control for a serious hazard.",
      "Stop Work Triggers shall be observable conditions any crew member can recognise without a judgement call.",
      "Keep every line short enough to read on a clipboard in the field.",
      "The Crew Acknowledgment section shall provide printed name, signature, and date lines, and shall state that signing means the signer participated in the review and understands the controls.",
    ],
    fields: [
      { key: "task_description", label: "Task being performed", kind: "textarea", required: true, placeholder: "The specific task, start to finish, in the order it is actually done" },
      { key: "location", label: "Location / work area", kind: "text", placeholder: "Building, level, bay, unit, or grid reference" },
      { key: "equipment_tools", label: "Equipment & tools in use", kind: "textarea", placeholder: "Powered equipment, lifting gear, hand tools, chemicals" },
      { key: "crew_size", label: "Crew size & trades involved", kind: "text", placeholder: "e.g. 4 ironworkers, 1 operator, 1 spotter" },
      { key: "permits_required", label: "Permits expected", kind: "text", placeholder: "e.g. hot work, confined space, energised electrical" },
    ],
  },
  {
    key: "daily_activity_plan",
    label: "Daily Activity Plan (DAP)",
    group: "Field Safety",
    summary: "One shift, one crew: what is being done, what could hurt someone, who is accountable.",
    documentKind: "Daily Activity Plan (DAP) / pre-task plan covering a single shift",
    fieldUse: true,
    humanReviewRequired: true,
    titlePlaceholder: "e.g. DAP — Mechanical Crew, Level 2 Piping",
    sections: [
      "Shift, Crew & Work Area",
      "Scope of Work for This Shift",
      "Hazards Expected Today",
      "Controls In Place Before Work Starts",
      "Permits, Inspections & Field Verification",
      "Simultaneous Operations & Adjacent Trades",
      "Emergency Information",
      "Pre-Task Briefing Acknowledgment",
    ],
    guidance: [
      "This document covers ONE shift and shall fit on a single page. A DAP that runs long does not get read, and a DAP that does not get read is not a control.",
      'Controls shall be written as completed conditions verified before work starts — "Barricades installed and signed at the north and east approaches", not "barricade the area".',
      "Call out simultaneous operations explicitly: which trade is working above, below, or adjacent, and how the conflict is managed.",
      "Every Field Verification line shall name who verifies and what they physically check.",
      "Use checkbox markers [ ] on anything that gets verified in the field.",
      "This is not a second JSA. Reference the governing JSA rather than repeating its step-by-step analysis.",
    ],
    fields: [
      { key: "shift_date", label: "Date / shift", kind: "text", placeholder: "e.g. Tuesday day shift, 0600–1630" },
      { key: "crew_and_supervisor", label: "Crew & supervisor", kind: "text", placeholder: "Contractor, crew size, foreman role" },
      { key: "work_area", label: "Work area", kind: "text", placeholder: "Building, level, unit, grid" },
      { key: "planned_work", label: "Work planned this shift", kind: "textarea", required: true, placeholder: "What the crew will actually accomplish today" },
      { key: "adjacent_work", label: "Adjacent or overhead work", kind: "textarea", placeholder: "Other trades working near, above, or below this crew" },
    ],
  },
  {
    key: "toolbox_talk",
    label: "Toolbox Talk",
    group: "Field Safety",
    summary: "A five-minute crew briefing on one topic, with a sign-off sheet.",
    documentKind: "toolbox talk / daily safety briefing on a single topic",
    fieldUse: true,
    humanReviewRequired: false,
    titlePlaceholder: "e.g. Dropped Objects During Overhead Work",
    sections: [
      "Topic & Why It Matters Here",
      "What Has Gone Wrong",
      "What We Require On This Site",
      "Discussion Questions",
      "Attendance & Acknowledgment",
    ],
    guidance: [
      "This is spoken aloud in five minutes. Write it to be read out, not studied.",
      '"What We Require On This Site" shall be three to six concrete, checkable requirements — not general advice.',
      "Tie the topic to the work actually happening on this site rather than to national statistics.",
      "Discussion Questions shall be open questions that surface site-specific conditions, not yes/no quiz items.",
      "Attendance shall provide printed name, signature, and date lines.",
    ],
    fields: [
      { key: "topic", label: "Topic", kind: "text", required: true, placeholder: "The one thing this talk covers" },
      { key: "trigger", label: "Why now?", kind: "textarea", placeholder: "Recent near-miss, upcoming task, audit finding, seasonal change" },
      { key: "audience", label: "Audience", kind: "text", placeholder: "e.g. mixed trades, new hires, operators" },
    ],
  },
  {
    key: "permit_package",
    label: "Permit-to-Work Package",
    group: "Field Safety",
    summary: "Pre-conditions, verifications and sign-offs required before high-hazard work may start.",
    documentKind: "permit-to-work package authorising a high-hazard activity",
    fieldUse: true,
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Hot Work Permit — Tank Farm Piping Tie-In",
    sections: [
      "Permit Type, Scope & Validity Period",
      "Authorised Personnel, Issuer & Competent Person",
      "Conditions That Shall Exist Before Work Starts",
      "Isolation, Testing & Monitoring Requirements",
      "Required PPE & Equipment",
      "Fire Watch / Attendant / Standby Duties",
      "Suspension & Cancellation Conditions",
      "Emergency & Rescue Plan",
      "Authorisation & Closure Signatures",
    ],
    guidance: [
      'Every item under "Conditions That Shall Exist Before Work Starts" shall be a physically verifiable state the issuer can confirm by walking the area — not an instruction to the crew. Write each as a checkbox line [ ].',
      "State the validity period explicitly and require re-issue when conditions change, when the shift changes, or when the permit expires.",
      "Name the atmospheric testing, isolation verification, or energy-isolation checks required, who is qualified to perform them, and how often they are repeated.",
      "Suspension conditions shall be unambiguous. State plainly that any person on site holds stop work authority.",
      "Closure shall require the issuer to verify the area was left safe, and shall be signed and dated separately from the authorisation.",
      "Name the issuing authority by role, never by an invented person.",
    ],
    fields: [
      {
        key: "permit_type",
        label: "Permit type",
        kind: "select",
        required: true,
        options: [
          "Hot work",
          "Confined space entry",
          "Energised electrical work",
          "Lockout / tagout",
          "Excavation & trenching",
          "Elevated / fall-hazard work",
          "Line breaking",
          "Critical lift",
          "Roof access",
          "Other high-hazard work",
        ],
      },
      { key: "work_description", label: "Work covered by the permit", kind: "textarea", required: true, placeholder: "Exactly what is authorised — and what is not" },
      { key: "location", label: "Location", kind: "text", placeholder: "Building, unit, equipment tag" },
      { key: "energy_sources", label: "Energy sources / hazardous materials present", kind: "textarea", placeholder: "Electrical, pressure, thermal, chemical, stored energy" },
      { key: "duration", label: "Expected duration", kind: "text", placeholder: "e.g. single shift, 3 days, until tie-in complete" },
    ],
  },
  {
    key: "corrective_action_notice",
    label: "Corrective Action Notice",
    group: "Field Safety",
    summary: "A documented finding, the required correction, the deadline, and the escalation path.",
    documentKind: "safety corrective action notice issued to a contractor or crew",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Corrective Action — Unprotected Leading Edge, Level 3",
    sections: [
      "Notice Details & Issuing Authority",
      "Observed Condition",
      "Requirement Not Met",
      "Immediate Action Taken",
      "Required Corrective Action",
      "Completion Deadline & Verification",
      "Escalation & Consequences",
      "Acknowledgment",
    ],
    guidance: [
      "Observed Condition shall be factual and free of blame or speculation — what was seen, where, and when.",
      "Requirement Not Met shall cite the specific site rule, contract expectation, or standard. Where no written rule applies, state plainly that the condition is unsafe and why.",
      "Required Corrective Action shall be a single unambiguous outcome with a responsible role and a dated deadline.",
      "Verification shall name who confirms closure and what documented evidence is required.",
      "Escalation shall state what happens if the deadline passes, in terms the contract can support.",
      "Name people by role, never by an invented name.",
    ],
    fields: [
      { key: "contractor", label: "Contractor / crew issued to", kind: "text", required: true, placeholder: "Company and responsible supervisor role" },
      { key: "observation", label: "What was observed", kind: "textarea", required: true, placeholder: "Facts only — condition, location, date, time" },
      { key: "severity", label: "Severity", kind: "select", options: ["Stop work — immediate", "High — correct before next shift", "Moderate — correct within 72 hours", "Low — correct within the week"] },
      { key: "immediate_action", label: "Immediate action already taken", kind: "textarea", placeholder: "Work stopped, area barricaded, crew removed, equipment tagged" },
      { key: "due_date", label: "Correction due by", kind: "text", placeholder: "Date or shift" },
    ],
  },
  {
    key: "incident_investigation",
    label: "Incident / Near-Miss Investigation",
    group: "Field Safety",
    summary: "Factual account, causal analysis, and corrective actions with owners and dates.",
    documentKind: "incident or near-miss investigation report",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Near-Miss Investigation — Dropped Wrench, Pipe Rack",
    sections: [
      "Incident Summary",
      "Sequence of Events",
      "People, Equipment & Conditions Involved",
      "Immediate Causes",
      "Contributing & Root Causes",
      "Controls That Were In Place",
      "Corrective & Preventive Actions",
      "Lessons Learned & Communication Plan",
      "Open Items Requiring Verification",
    ],
    guidance: [
      "Separate fact from inference. Sequence of Events shall contain only what is established; analysis belongs in the cause sections.",
      "Do not assign personal blame. Root causes are failures of system, planning, supervision, design, and training.",
      "Every corrective action shall carry a responsible role, a due date, and a verification method.",
      "Where a fact is not yet known, list it under Open Items Requiring Verification rather than filling the gap.",
      "Do not speculate about injury severity, medical outcome, or OSHA recordability — those are human determinations and shall be flagged as such.",
    ],
    fields: [
      { key: "incident_type", label: "Type", kind: "select", required: true, options: ["Near miss", "First aid", "Recordable injury", "Property damage", "Environmental release", "Fire", "Equipment failure", "Utility strike", "Security", "Other"] },
      { key: "what_happened", label: "What happened", kind: "textarea", required: true, placeholder: "Known facts in the order they occurred" },
      { key: "when_where", label: "When & where", kind: "text", placeholder: "Date, time, shift, exact location" },
      { key: "people_involved", label: "People involved (roles, not names)", kind: "textarea", placeholder: "e.g. two pipefitters, one signal person, one operator" },
      { key: "existing_controls", label: "Controls that were in place", kind: "textarea", placeholder: "Permits, JSA, barricades, PPE, training in effect at the time" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Safety Program — the governing documents a site or client is held to
// ---------------------------------------------------------------------------

const safetyProgram: readonly GeneratorSpec[] = [
  {
    key: "site_safety_plan",
    label: "Site-Specific Safety Plan",
    group: "Safety Program",
    summary: "The condensed, reviewer-ready plan a client requires as a submittal.",
    documentKind: "Site-Specific Safety Plan (SSSP) in condensed professional plan format",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Site-Specific Safety Plan — [PROJECT NAME]",
    sections: [
      "Purpose, Scope & Applicability",
      "Project Description & Site Conditions",
      "Roles, Responsibilities & Authority",
      "Hazard Identification & Risk Control",
      "High-Hazard Activities & Permit Requirements",
      "Training, Orientation & Competency",
      "Inspections, Audits & Field Verification",
      "Incident Reporting & Investigation",
      "Emergency Action & Site Response",
      "Subcontractor Management",
      "Stop Work Authority",
      "Plan Review, Revision & Acknowledgment",
    ],
    guidance: [
      "This is a submittal a client reviewer will read. It shall be complete but condensed — a serious professional plan, not a long generic manual.",
      "Roles, Responsibilities & Authority shall be a table naming each role, what that role is accountable for, and what authority it holds.",
      "Stop Work Authority shall state without qualification that any person on site may stop work, that there shall be no retaliation, and how work resumes.",
      "Every requirement shall be verifiable. Where a section would otherwise be generic, replace it with a site-specific requirement or a NEEDS YOUR INPUT line.",
      "Close with an acknowledgment block and a revision log.",
    ],
    fields: [
      { key: "project_description", label: "Project description", kind: "textarea", required: true, placeholder: "Type of work, duration, phases, peak headcount" },
      { key: "site_conditions", label: "Site conditions", kind: "textarea", placeholder: "Occupied facility, live utilities, weather exposure, access constraints, adjacent operations" },
      { key: "high_hazard_activities", label: "High-hazard activities expected", kind: "textarea", placeholder: "e.g. work at height, confined space, energised work, critical lifts, excavation" },
      { key: "client_requirements", label: "Client / owner requirements", kind: "textarea", placeholder: "Owner safety standards this plan must satisfy" },
      { key: "project_phases", label: "Phases covered", kind: "text", placeholder: "e.g. demolition through commissioning" },
    ],
  },
  {
    key: "contractor_expectations",
    label: "Contractor Safety Expectations",
    group: "Safety Program",
    summary: "What a subcontractor is required to do, before and during work, in contract-grade terms.",
    documentKind: "contractor and subcontractor safety expectations document, suitable as a contract exhibit",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Contractor Safety Expectations — [PROJECT NAME]",
    sections: [
      "Purpose & Applicability",
      "Prequalification Requirements",
      "Pre-Mobilisation Submittals",
      "Site Orientation & Training Requirements",
      "Daily Planning & Documentation Requirements",
      "Supervision & Competent Person Requirements",
      "Minimum Site Safety Rules",
      "Inspection, Audit & Access Rights",
      "Incident Reporting Obligations",
      "Non-Compliance, Escalation & Removal",
      "Acknowledgment",
    ],
    guidance: [
      "Write this so a subcontractor cannot later claim they did not understand what was required. Each expectation shall be specific enough to enforce and to measure.",
      "Pre-Mobilisation Submittals shall be a list with a due date relative to mobilisation for each item.",
      "Non-Compliance shall define escalation in defined steps with named consequences at each step, up to and including removal from site.",
      "State the company's right to inspect, audit, and stop the contractor's work at any time.",
      "Avoid softening language entirely. This document is only useful if every line is enforceable.",
    ],
    fields: [
      { key: "scope_of_contract", label: "Scope of contracted work", kind: "textarea", required: true, placeholder: "What this contractor is on site to do" },
      { key: "submittals_required", label: "Submittals required before mobilisation", kind: "textarea", placeholder: "e.g. safety plan, JSAs, training records, insurance, competent person designations" },
      { key: "site_rules", label: "Site rules that must be included", kind: "textarea", placeholder: "Non-negotiable rules specific to this site" },
      { key: "escalation_preference", label: "Escalation approach", kind: "select", options: ["Progressive — verbal, written, stop work, removal", "Immediate stop work for life-safety, progressive otherwise", "Zero tolerance for defined critical rules"] },
    ],
  },
  {
    key: "safety_coverage_plan",
    label: "Safety Coverage Plan",
    group: "Safety Program",
    summary: "Defensible safety staffing: ratios, risk weighting, gaps, and escalation.",
    documentKind: "jobsite safety staffing and coverage plan, written to justify coverage to an owner or executive",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Safety Coverage Plan — [PROJECT NAME], Q4 Ramp",
    sections: [
      "Purpose & Basis of the Coverage Model",
      "Scope of Work Driving Coverage",
      "Risk Weighting & Coverage Drivers",
      "Coverage Matrix by Shift & Area",
      "Minimum Coverage Requirements",
      "Gap Analysis",
      "Escalation & Contingency",
      "Review Triggers",
    ],
    guidance: [
      "This document exists to be defended. Every coverage number shall be tied to a stated driver — headcount, shift pattern, high-hazard activity, area separation, or client requirement — not to a preference.",
      "Coverage Matrix shall be a table: shift, area, headcount covered, safety personnel assigned, and the driver that sets that number.",
      "Minimum Coverage Requirements shall state the floor below which work does not proceed, in enforceable terms.",
      "Gap Analysis shall state each gap, the risk it creates, and the interim control — never present a gap without an interim control or an explicit escalation.",
      "Review Triggers shall be concrete events: headcount change, added shift, new high-hazard phase, turnaround, or shutdown.",
    ],
    fields: [
      { key: "headcount", label: "Craft headcount & trajectory", kind: "textarea", required: true, placeholder: "Current headcount, peak, and when the ramp happens" },
      { key: "shift_pattern", label: "Shift pattern", kind: "text", placeholder: "e.g. day and night, 6 days, plus weekend outage coverage" },
      { key: "areas", label: "Work areas requiring separate coverage", kind: "textarea", placeholder: "Physically separated areas that cannot be covered by one person" },
      { key: "high_risk_drivers", label: "High-risk activities driving coverage", kind: "textarea", placeholder: "Confined space, critical lifts, energised work, simultaneous operations" },
      { key: "current_staffing", label: "Current safety staffing", kind: "text", placeholder: "e.g. 1 safety director, 2 field safety specialists, days only" },
    ],
  },
  {
    key: "emergency_action_plan",
    label: "Emergency Action Plan",
    group: "Safety Program",
    summary: "Who does what, where people go, and how it is communicated when something goes wrong.",
    documentKind: "site Emergency Action Plan",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Emergency Action Plan — [SITE / LOCATION]",
    sections: [
      "Purpose, Scope & Applicability",
      "Emergency Types Covered",
      "Alarm, Notification & Communication",
      "Evacuation Routes & Muster Points",
      "Accountability & Headcount",
      "Roles & Assigned Responsibilities",
      "Medical Response & First Aid",
      "Rescue Provisions for High-Hazard Work",
      "External Emergency Services & Site Access",
      "Drills, Training & Plan Review",
    ],
    guidance: [
      "Every emergency type covered shall have a named first action and a named responsible role.",
      "Accountability shall state exactly how headcount is reconciled and who declares all-clear.",
      "Rescue Provisions shall be specific to the high-hazard work on this site — confined space and fall rescue shall never rely on calling emergency services alone.",
      "Use [MUSTER POINT], [EMERGENCY NUMBER], and [SITE ADDRESS] placeholders rather than inventing any of them.",
      "State drill frequency and who documents them.",
    ],
    fields: [
      { key: "site_layout", label: "Site layout & access", kind: "textarea", required: true, placeholder: "Buildings, gates, roads, areas where access is restricted" },
      { key: "emergency_types", label: "Emergency types to cover", kind: "textarea", placeholder: "e.g. fire, medical, severe weather, chemical release, utility strike, active threat" },
      { key: "onsite_resources", label: "On-site response resources", kind: "textarea", placeholder: "First aid trained personnel, AED locations, rescue team, fire equipment" },
      { key: "occupied_facility", label: "Occupied or operating facility?", kind: "select", options: ["Yes — client operations continue during our work", "Partially — some areas occupied", "No — construction site only"] },
    ],
  },
  { key: "sop", label: "Standard Operating Procedure", group: "Safety Program", summary: "Step-by-step procedure for a repeatable task, written to be followed exactly.", documentKind: "Standard Operating Procedure (SOP)", humanReviewRequired: true, titlePlaceholder: "e.g. Forklift Operation SOP",
    sections: ["Purpose", "Scope", "Definitions", "Responsibilities", "Required PPE", "Hazards & Controls", "Procedure (numbered steps)", "Emergency & Reporting", "References", "Revision History"],
    guidance: [
      "The Procedure section shall be numbered steps in the order performed, each one a single action a person can complete and verify.",
      "Where a step has a hazard, state the control at that step rather than only in the Hazards & Controls section.",
    ],
    fields: [
      { key: "procedure_trigger", label: "When is this procedure performed?", kind: "text", placeholder: "e.g. before each use, at every shift change, on receipt of material" },
      { key: "equipment", label: "Equipment or system covered", kind: "text", placeholder: "Specific equipment, model class, or system" },
    ],
  },
  { key: "policy", label: "Policy", group: "Safety Program", summary: "A standing rule with defined roles, requirements, and consequences.", documentKind: "workplace safety Policy", humanReviewRequired: true, titlePlaceholder: "e.g. Fall Protection Policy",
    sections: ["Purpose", "Scope", "Policy Statement", "Roles & Responsibilities", "Compliance Requirements", "Enforcement & Consequences", "Review Cycle", "References"],
    guidance: [
      "The Policy Statement shall be a single paragraph a person can quote. Everything else supports it.",
      "Enforcement & Consequences shall be specific enough to apply consistently, and shall state who applies them.",
    ],
    fields: [
      { key: "policy_driver", label: "What is driving this policy?", kind: "textarea", placeholder: "Incident history, client requirement, regulatory change, audit finding" },
      { key: "applies_to", label: "Who is bound by this policy?", kind: "text", placeholder: "e.g. all personnel and subcontractors on [PROJECT NAME]" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Governance — verification, tracking, and the things auditors ask for
// ---------------------------------------------------------------------------

const governance: readonly GeneratorSpec[] = [
  {
    key: "audit_checklist",
    label: "Audit / Inspection Checklist",
    group: "Governance",
    summary: "A walkdown checklist with acceptance criteria and finding classification.",
    documentKind: "safety audit or site inspection checklist",
    fieldUse: true,
    humanReviewRequired: false,
    titlePlaceholder: "e.g. Weekly Site Safety Walkdown Checklist",
    sections: [
      "Audit Scope, Frequency & Auditor",
      "Finding Classification",
      "Checklist Items & Acceptance Criteria",
      "Findings Log",
      "Corrective Action & Closure",
      "Sign-Off",
    ],
    guidance: [
      "Every checklist item shall be written as a checkbox line [ ] with an acceptance criterion a reviewer can test — not as an open question.",
      'Avoid items that invite a subjective answer. "Housekeeping acceptable" is not an item; "Walkways clear of material and cord runs, minimum 36 inches" is.',
      "Finding Classification shall define each severity level and the correction timeframe attached to it.",
      "Group items by area or by activity so the auditor walks the site once, not three times.",
      "Provide space for finding number, location, severity, owner, and due date in the Findings Log.",
    ],
    fields: [
      { key: "audit_scope", label: "What is being audited", kind: "textarea", required: true, placeholder: "Areas, activities, contractors, or program elements in scope" },
      { key: "frequency", label: "Frequency", kind: "select", options: ["Daily", "Weekly", "Monthly", "Quarterly", "Phase-based", "Client audit preparation", "One-time assessment"] },
      { key: "auditor_role", label: "Who performs it", kind: "text", placeholder: "e.g. Site Safety Director with area superintendent" },
      { key: "standards_basis", label: "Standards or requirements it audits against", kind: "textarea", placeholder: "Site safety plan sections, client standards, regulatory requirements" },
    ],
  },
  {
    key: "field_safety_report",
    label: "Field Safety Report",
    group: "Governance",
    summary: "Daily, weekly, or monthly written record of what happened on site.",
    documentKind: "recurring field safety report",
    humanReviewRequired: false,
    titlePlaceholder: "e.g. Weekly Safety Report — [PROJECT NAME]",
    sections: [
      "Reporting Period & Site Status",
      "Work Performed & Headcount",
      "Safety Activities Completed",
      "Observations & Findings",
      "Incidents & Near Misses",
      "Open Corrective Actions",
      "Look-Ahead & Upcoming High-Hazard Work",
      "Support Required",
    ],
    guidance: [
      "This report shall demonstrate control of the site, not activity for its own sake. Lead with status and risk, not with counts of talks delivered.",
      "Open Corrective Actions shall be a table: finding, owner role, due date, and current status. Aged items shall be called out explicitly.",
      "Look-Ahead shall name the high-hazard work coming and what is being put in place before it starts.",
      "Support Required shall be specific asks with a named decision-maker role — not a general request for resources.",
      "Report only what the author supplied. Where a figure is unknown, mark it NEEDS YOUR INPUT rather than estimating.",
    ],
    fields: [
      { key: "period", label: "Reporting period", kind: "text", required: true, placeholder: "e.g. week ending [EFFECTIVE DATE]" },
      { key: "audience", label: "Audience", kind: "select", options: ["Client / owner", "Internal leadership", "Project team", "Field supervision"] },
      { key: "activity_summary", label: "What happened this period", kind: "textarea", required: true, placeholder: "Work performed, safety activities, observations, incidents" },
      { key: "open_items", label: "Open corrective actions", kind: "textarea", placeholder: "Findings still open, with owner and due date" },
      { key: "lookahead", label: "Look-ahead", kind: "textarea", placeholder: "High-hazard work coming in the next period" },
    ],
  },
  {
    key: "certification_matrix",
    label: "Certification & Training Matrix",
    group: "Governance",
    summary: "Who is qualified for what, what expires when, and what work is blocked without it.",
    documentKind: "certification, training and competency tracking matrix with an expiration control process",
    humanReviewRequired: false,
    titlePlaceholder: "e.g. Certification & Training Matrix — [PROJECT NAME]",
    sections: [
      "Purpose & Scope",
      "Required Certifications by Role",
      "Required Certifications by Activity",
      "Validity Periods & Renewal Lead Times",
      "Verification at Onboarding",
      "Expiration Monitoring & Escalation",
      "Work Restrictions for Lapsed Credentials",
      "Record Retention",
    ],
    guidance: [
      "Required Certifications by Activity shall be a table linking each high-hazard activity to the credential that authorises it — this is the table that prevents unqualified work.",
      "Renewal Lead Times shall state how far in advance a renewal is triggered, so a lapse never happens silently.",
      "Work Restrictions shall state plainly that work requiring a lapsed credential shall not proceed, and who enforces that.",
      "Verification at Onboarding shall name what evidence is accepted and who checks it.",
      "Do not invent certification names or validity periods you are unsure of — flag them NEEDS YOUR INPUT.",
    ],
    fields: [
      { key: "roles_covered", label: "Roles covered", kind: "textarea", required: true, placeholder: "e.g. operators, riggers, competent persons, supervisors, general craft" },
      { key: "activities", label: "Activities requiring credentials", kind: "textarea", placeholder: "e.g. confined space entry, crane operation, rigging, LOTO, forklift" },
      { key: "client_requirements", label: "Client-required credentials", kind: "textarea", placeholder: "Owner-specific training, site badging, background requirements" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Commercial — client-facing documents around the 12-stage lifecycle.
// Proposals are NOT here: lib/proposals owns that pipeline end to end, with its
// own type profiles, pricing, revisions, DocuSign, and share links. These are
// the documents that sit either side of it.
// ---------------------------------------------------------------------------

const commercial: readonly GeneratorSpec[] = [
  {
    key: "scope_of_work",
    label: "Scope of Work",
    group: "Commercial",
    summary: "What is delivered, what is not, and what the client is responsible for.",
    documentKind: "Scope of Work for a safety services engagement",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Scope of Work — Site Safety Coverage, [CLIENT / OWNER]",
    sections: [
      "Engagement Overview",
      "Services Included",
      "Deliverables & Frequency",
      "Services Explicitly Excluded",
      "Client Responsibilities & Site Access",
      "Personnel, Coverage & Schedule",
      "Assumptions",
      "Change Control",
      "Acceptance",
    ],
    guidance: [
      "Services Explicitly Excluded carries as much weight as what is included. Name the things a client commonly assumes are covered and state that they are not.",
      "Deliverables shall each state what it is, how often it is produced, and who receives it.",
      "Client Responsibilities shall be specific — access, badging, information, decision turnaround — because a missed client responsibility is what puts a schedule at risk.",
      "Assumptions shall be the conditions the pricing and coverage depend on. If one fails, change control applies.",
      "Do not state prices, rates, or payment terms — those live in the proposal and the agreement.",
      "Do not invent client names, dates, or personnel. Use placeholders.",
    ],
    fields: [
      { key: "services", label: "Services to be provided", kind: "textarea", required: true, placeholder: "What the company is actually being engaged to do" },
      { key: "deliverables", label: "Deliverables", kind: "textarea", placeholder: "Reports, plans, audits, dashboards, training — and how often" },
      { key: "exclusions", label: "Known exclusions", kind: "textarea", placeholder: "What the client might assume is included but is not" },
      { key: "duration", label: "Term / duration", kind: "text", placeholder: "e.g. 12 months, project duration, phase-based" },
      { key: "coverage_model", label: "Coverage model", kind: "text", placeholder: "e.g. full-time on site days, on-call nights, remote support" },
    ],
  },
  {
    key: "pilot_agreement",
    label: "Pilot / Beta Program Agreement",
    group: "Commercial",
    summary: "Boundaries, access, feedback obligations and exit terms for a limited pilot.",
    documentKind: "pilot or beta program agreement for a limited software or service rollout",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Pilot Program Agreement — [CLIENT / OWNER]",
    sections: [
      "Purpose & Pilot Objectives",
      "Pilot Scope & Duration",
      "What Is Included in the Pilot",
      "What Is Explicitly Out of Scope",
      "Access, Roles & Permissions Granted",
      "Participant Responsibilities",
      "Feedback & Review Cadence",
      "Data Handling & Confidentiality",
      "Success Criteria & Evaluation",
      "Support & Response Expectations",
      "Exit, Extension & Conversion",
      "Acknowledgment",
    ],
    guidance: [
      "A pilot without boundaries becomes an unpaid open-ended engagement. Every section shall tighten scope rather than leave it open.",
      "Access shall be described as a permission model — what each named role can see and do — not as a job title with implied access.",
      "Feedback obligations shall be concrete: what form, how often, and from whom. A pilot that produces no feedback has failed regardless of uptime.",
      "Success Criteria shall be measurable and agreed before the pilot starts, and shall state who evaluates them.",
      "Exit terms shall cover what happens to the participant's data and access when the pilot ends, in every outcome — conversion, extension, or termination.",
      "This document has legal effect. Flag every term that requires counsel review as NEEDS YOUR INPUT rather than drafting it as settled.",
    ],
    fields: [
      { key: "pilot_scope", label: "What the pilot covers", kind: "textarea", required: true, placeholder: "Modules, sites, crews, or workflows included" },
      { key: "duration", label: "Pilot duration", kind: "text", placeholder: "e.g. 90 days from [EFFECTIVE DATE]" },
      { key: "participants", label: "Participants & roles", kind: "textarea", placeholder: "How many users, which roles, which sites" },
      { key: "success_criteria", label: "What success looks like", kind: "textarea", placeholder: "Measurable outcomes that decide whether this converts" },
      { key: "access_model", label: "Access model", kind: "select", options: ["Permission-based — access granted per capability", "Role-based — access follows a defined role", "Single shared pilot role"] },
      { key: "commercial_terms", label: "Commercial terms", kind: "select", options: ["No fee — feedback in exchange for access", "Discounted pilot fee", "Paid pilot credited against a future contract", "To be determined"] },
    ],
  },
  {
    key: "client_onboarding_packet",
    label: "Client Onboarding Packet",
    group: "Commercial",
    summary: "The first thirty days: contacts, access, milestones, and what the client owes us when.",
    documentKind: "client onboarding packet issued at the start of an engagement",
    humanReviewRequired: false,
    titlePlaceholder: "e.g. Onboarding Packet — [CLIENT / OWNER]",
    sections: [
      "Welcome & Engagement Summary",
      "Key Contacts & Escalation Path",
      "Onboarding Milestones & Dates",
      "Information & Access We Need From You",
      "Systems, Accounts & Permissions",
      "Site Requirements & Badging",
      "Communication & Reporting Cadence",
      "First 30 Days at a Glance",
      "Open Questions",
    ],
    guidance: [
      'Every item under "Information & Access We Need From You" shall have an owner and a due date, expressed relative to the start date.',
      "Key Contacts shall be a table of role, responsibility, and escalation order. Use placeholders for names.",
      "First 30 Days at a Glance shall be a short table of week, milestone, and owner.",
      "Keep this to something a client can read in one sitting on day one.",
    ],
    fields: [
      { key: "engagement_summary", label: "What we are delivering", kind: "textarea", required: true, placeholder: "Short summary of the engagement" },
      { key: "start_date", label: "Start date", kind: "text", placeholder: "e.g. [EFFECTIVE DATE]" },
      { key: "client_inputs", label: "What we need from the client", kind: "textarea", placeholder: "Documents, access, contacts, site information, badging" },
      { key: "reporting_cadence", label: "Reporting cadence", kind: "text", placeholder: "e.g. weekly written report, monthly review call" },
    ],
  },
];

// ---------------------------------------------------------------------------
// People — HR documents. Anything that affects someone's employment is
// humanReviewRequired without exception.
// ---------------------------------------------------------------------------

const people: readonly GeneratorSpec[] = [
  {
    key: "job_description",
    label: "Job Description",
    group: "People",
    summary: "Accountabilities, requirements, and what good performance looks like.",
    documentKind: "job description for an internal role",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Field Safety Specialist — [SITE / LOCATION]",
    sections: [
      "Role Summary",
      "Reporting Relationships",
      "Core Accountabilities",
      "Required Qualifications & Certifications",
      "Preferred Experience",
      "Physical & Site Requirements",
      "Authority Held by This Role",
      "How Performance Is Measured",
    ],
    guidance: [
      "Core Accountabilities shall be outcomes the person is answerable for, not a list of activities they perform.",
      "Authority Held by This Role shall state explicitly what the role can decide, approve, and stop — for safety roles this includes stop work authority.",
      "How Performance Is Measured shall be concrete enough to use in a review conversation.",
      "Do not state salary, benefits, or employment classification — those are separate decisions.",
      "Physical & Site Requirements shall describe the job's actual demands without reference to any protected characteristic.",
    ],
    fields: [
      { key: "role_title", label: "Role title", kind: "text", required: true, placeholder: "The title as it will be posted" },
      { key: "reports_to", label: "Reports to", kind: "text", placeholder: "Role, not a person" },
      { key: "responsibilities", label: "What this role is accountable for", kind: "textarea", required: true, placeholder: "The outcomes this person owns" },
      { key: "required_credentials", label: "Required credentials", kind: "textarea", placeholder: "Certifications, licences, years of experience" },
      { key: "work_environment", label: "Work environment", kind: "text", placeholder: "e.g. active construction site, multi-shift, travel required" },
    ],
  },
  {
    key: "offer_letter",
    label: "Offer Letter",
    group: "People",
    summary: "Role, start date, terms and conditions of an offer of employment.",
    documentKind: "employment offer letter",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Offer of Employment — Field Safety Specialist",
    sections: [
      "Offer Summary",
      "Position & Reporting",
      "Start Date & Location",
      "Compensation & Pay Schedule",
      "Benefits Summary",
      "Conditions of Employment",
      "Pre-Employment Requirements",
      "Acceptance",
    ],
    guidance: [
      "This document has legal effect. Every term shall be exactly as supplied by the author — never infer, round, or improve a figure, date, or benefit.",
      "Any term the author did not supply shall appear as NEEDS YOUR INPUT, not as a plausible default.",
      "Conditions of Employment shall state clearly what the offer is contingent on and what happens if a condition is not met.",
      "Do not characterise the employment relationship, its duration, or its termination terms beyond what the author supplied — flag those for counsel or HR review.",
      "Use [CANDIDATE NAME] and [EFFECTIVE DATE] placeholders rather than inventing either.",
    ],
    fields: [
      { key: "position", label: "Position offered", kind: "text", required: true, placeholder: "Title and department" },
      { key: "compensation", label: "Compensation", kind: "text", placeholder: "Exactly as it should appear — leave blank if not yet decided" },
      { key: "start_date", label: "Start date", kind: "text", placeholder: "e.g. [EFFECTIVE DATE]" },
      { key: "work_location", label: "Work location", kind: "text", placeholder: "Site, office, or remote arrangement" },
      { key: "conditions", label: "Conditions of employment", kind: "textarea", placeholder: "Background check, drug screen, credential verification, I-9" },
      { key: "benefits", label: "Benefits to summarise", kind: "textarea", placeholder: "Only what has actually been decided" },
    ],
  },
  {
    key: "onboarding_plan",
    label: "Employee 30/60/90 Plan",
    group: "People",
    summary: "What a new hire learns, does, and owns across their first ninety days.",
    documentKind: "30/60/90 day onboarding and ramp plan for a new employee",
    humanReviewRequired: false,
    titlePlaceholder: "e.g. 30/60/90 Plan — Field Safety Specialist",
    sections: [
      "Role & Ramp Objective",
      "Before Day One",
      "Days 1–30: Learn",
      "Days 31–60: Contribute",
      "Days 61–90: Own",
      "Required Training & Certifications",
      "Check-In Schedule",
      "What Success Looks Like at 90 Days",
    ],
    guidance: [
      "Each phase shall have between three and six outcomes, each with a named supporting role — not a list of reading material.",
      "Days 61–90 shall name what the person independently owns by the end of the ramp.",
      "Required Training shall distinguish what must be complete before site access from what can follow.",
      "Check-In Schedule shall name who holds each check-in and what is reviewed.",
    ],
    fields: [
      { key: "role_title", label: "Role", kind: "text", required: true, placeholder: "Title of the new hire's role" },
      { key: "manager_role", label: "Manager / mentor role", kind: "text", placeholder: "Who supports the ramp" },
      { key: "first_projects", label: "Work they will pick up", kind: "textarea", placeholder: "Sites, clients, systems, or programs they will take on" },
      { key: "required_training", label: "Required training & credentials", kind: "textarea", placeholder: "What they need before site access" },
    ],
  },
  {
    key: "performance_review",
    label: "Performance Review Packet",
    group: "People",
    summary: "Structured review against accountabilities, with development actions.",
    documentKind: "employee performance review packet",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Annual Performance Review — Field Safety Specialist",
    sections: [
      "Review Period & Role",
      "Accountabilities Reviewed",
      "Performance Against Each Accountability",
      "Strengths Demonstrated",
      "Development Areas",
      "Goals for the Next Period",
      "Support & Resources Required",
      "Employee Comments & Acknowledgment",
    ],
    guidance: [
      "Assess only against what the author supplied. Never invent an achievement, a shortfall, a rating, or an example.",
      "Development Areas shall be written as specific, actionable changes with a support mechanism attached — never as a character judgement.",
      "Goals shall be measurable and time-bound, with a stated review point.",
      "Leave the Employee Comments section blank for the employee to complete.",
      "Where the author supplied no evidence for a section, mark it NEEDS YOUR INPUT.",
    ],
    fields: [
      { key: "role_title", label: "Role", kind: "text", required: true, placeholder: "Role being reviewed" },
      { key: "review_period", label: "Review period", kind: "text", placeholder: "e.g. calendar year, or hire date to present" },
      { key: "accountabilities", label: "Accountabilities being reviewed", kind: "textarea", required: true, placeholder: "The outcomes this role owns" },
      { key: "evidence", label: "Evidence & observations", kind: "textarea", placeholder: "What actually happened — results, examples, feedback received" },
      { key: "development_focus", label: "Development focus", kind: "textarea", placeholder: "Where growth is needed and why" },
    ],
  },
  {
    key: "disciplinary_notice",
    label: "Employee Disciplinary Notice",
    group: "People",
    summary: "Documented performance or conduct concern, expectation, and consequence.",
    documentKind: "written employee disciplinary or performance notice",
    humanReviewRequired: true,
    titlePlaceholder: "e.g. Written Notice — Attendance",
    sections: [
      "Notice Details",
      "Prior Discussions on This Matter",
      "Concern Documented",
      "Expectation Going Forward",
      "Support Provided",
      "Timeframe & Review Point",
      "Consequence of No Improvement",
      "Employee Comments & Acknowledgment",
    ],
    guidance: [
      "Document only the facts the author supplied — date, conduct, and impact. Never characterise motive, attitude, or personality.",
      "Expectation Going Forward shall be a specific observable behaviour or standard, with a date by which it applies.",
      "Consequence shall be stated plainly but shall not go beyond what the author specified. Never invent a termination threat.",
      "Leave Employee Comments blank for the employee.",
      "This document carries employment-law exposure. Flag every element requiring HR or counsel review as NEEDS YOUR INPUT.",
    ],
    fields: [
      { key: "notice_level", label: "Notice level", kind: "select", required: true, options: ["Documented verbal discussion", "First written notice", "Final written notice", "Performance improvement plan"] },
      { key: "concern", label: "Concern being documented", kind: "textarea", required: true, placeholder: "Facts only — what happened, when, and the impact" },
      { key: "prior_discussions", label: "Prior discussions", kind: "textarea", placeholder: "Previous conversations or notices on this matter, with dates" },
      { key: "expectation", label: "Expectation going forward", kind: "textarea", placeholder: "The specific standard required, and by when" },
      { key: "support", label: "Support offered", kind: "textarea", placeholder: "Training, coaching, schedule adjustment, mentoring" },
    ],
  },
  {
    key: "credential_expiration_notice",
    label: "Credential Expiration Notice",
    group: "People",
    summary: "Advance notice that a certification lapses, and what stops if it does.",
    documentKind: "notice that an employee certification or credential is approaching expiration",
    humanReviewRequired: false,
    titlePlaceholder: "e.g. Credential Expiration Notice — Confined Space Entry",
    sections: [
      "Notice Details",
      "Credential Expiring",
      "Work This Credential Authorises",
      "What Stops If It Lapses",
      "Renewal Steps & Owner",
      "Deadline & Escalation",
      "Acknowledgment",
    ],
    guidance: [
      "Lead with the date and the consequence. This notice exists to prevent a lapse, not to record one.",
      "What Stops If It Lapses shall name the specific activities the person may no longer perform, in enforceable terms.",
      "Renewal Steps shall be numbered actions with an owner for each — including which steps the company performs.",
      "Escalation shall state who is notified if the renewal is not complete by the deadline.",
      "Keep it to a single page.",
    ],
    fields: [
      { key: "credential", label: "Credential", kind: "text", required: true, placeholder: "Exact name of the certification or licence" },
      { key: "expiration", label: "Expiration date", kind: "text", placeholder: "e.g. [EFFECTIVE DATE]" },
      { key: "affected_work", label: "Work this credential authorises", kind: "textarea", placeholder: "What the person may not do without it" },
      { key: "renewal_process", label: "Renewal process", kind: "textarea", placeholder: "Course, provider, lead time, who schedules it" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

export const generatorRegistry: readonly GeneratorSpec[] = [
  ...fieldSafety,
  ...safetyProgram,
  ...governance,
  ...commercial,
  ...people,
];
