-- Reconcile schema drift: client_proposals.form_data / client_proposal_revisions.form_data
--
-- MODULE_ID: client_proposals (follow-up to 20260729120000_client_proposals.sql)
--
-- BACKGROUND
--   Production (project kmwgyoalstydoejqjemy) carries a nullable `form_data jsonb`
--   column on both client_proposals and client_proposal_revisions. No migration in
--   supabase/migrations/ creates it and no application code reads or writes it — it
--   was applied directly to the live database outside the migration history. It
--   surfaced on 2026-07-29 when lib/supabase/types.ts was regenerated from prod.
--
--   Consequence without this file: an environment rebuilt from migrations (staging,
--   a fresh branch database, local dev) would NOT have the column, so the checked-in
--   generated types would not match that database.
--
--   This migration is additive and forward-only. It makes migrations describe what
--   production already has; it does not remove the column. Dropping `form_data`
--   is a STOP condition under CLAUDE.md and requires explicit human sign-off — see
--   "IF THIS COLUMN IS UNWANTED" below.
--
-- SHAPE (verified against production via the PostgREST schema, 2026-07-29)
--   form_data  jsonb  NULL  (nullable, no default, no constraint, no index)
--   Both tables held 0 rows at the time of verification, so no data depends on it.
--
-- SECURITY
--   No new table, policy, or grant. The column inherits the RLS already enabled on
--   both tables by 20260729120000_client_proposals.sql: active portal employees may
--   read/insert/update proposals, revisions stay append-only, delete stays admin-only.
--
-- ROLLBACK
--   This migration is idempotent and additive; rolling it back is normally
--   unnecessary. To reverse it on an environment that did NOT already have the
--   column (i.e. NOT production), and only after confirming no rows hold data:
--     select count(*) from public.client_proposals where form_data is not null;
--     select count(*) from public.client_proposal_revisions where form_data is not null;
--     alter table public.client_proposal_revisions drop column if exists form_data;
--     alter table public.client_proposals drop column if exists form_data;
--
-- IF THIS COLUMN IS UNWANTED
--   Nothing in the codebase uses form_data. If the intent is to remove it rather
--   than keep it, do NOT edit this file — write a separate, signed-off drop
--   migration so the add/drop pair stays legible in the history, and rehearse it on
--   a staging branch first per the release gates in CLAUDE.md.

alter table public.client_proposals
  add column if not exists form_data jsonb;

alter table public.client_proposal_revisions
  add column if not exists form_data jsonb;

comment on column public.client_proposals.form_data is
  'Unstructured proposal form payload. Added directly to production outside the migration history and reconciled by migration 20260729130000. Currently unused by application code - treat as reserved until a module claims it.';

comment on column public.client_proposal_revisions.form_data is
  'Snapshot of client_proposals.form_data at the time this revision was saved. Added directly to production outside the migration history and reconciled by migration 20260729130000. Currently unused by application code.';
